// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/country": {
            "get": {
                "description": "Возвращает страны",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "country"
                ],
                "summary": "Получение стран",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/httpgin.Get_CountryById_Response"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Редактирует страну",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "country"
                ],
                "summary": "Редактирование страны",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Данные страны",
                        "name": "country",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpgin.Update_CountryById_Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Update_CountryById_Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет страну",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "country"
                ],
                "summary": "Добавление страну",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Данные страны",
                        "name": "country",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpgin.Create_Country_Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Create_Country_Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет страну",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "country"
                ],
                "summary": "Удаление страны",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "ID страны",
                        "name": "country",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpgin.Delete_CountryById_Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Delete_CountryById_Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    }
                }
            }
        },
        "/api/v1/country/{country_id}": {
            "get": {
                "description": "Возвращает страну",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "country"
                ],
                "summary": "Получение страны",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID страны",
                        "name": "country_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Get_CountryById_Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    }
                }
            }
        },
        "/api/v2/country": {
            "get": {
                "description": "Возвращает страны",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "country"
                ],
                "summary": "Получение стран",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Filter,Pagination,Sort",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpgin.Get_All_Country_Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Get_All_Country_Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    }
                }
            }
        },
        "/auth": {
            "post": {
                "description": "Авторизует пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация",
                "parameters": [
                    {
                        "description": "Данные пользователя",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpgin.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpgin.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Регистрирует пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрирует пользователя",
                "parameters": [
                    {
                        "description": "Данные пользователя",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpgin.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": ""
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpgin.Error_Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httpgin.AuthRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "httpgin.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "httpgin.Create_Country_Request": {
            "type": "object",
            "properties": {
                "country_area": {
                    "type": "string"
                },
                "country_capital": {
                    "type": "string"
                },
                "country_title": {
                    "type": "string"
                }
            }
        },
        "httpgin.Create_Country_Response": {
            "type": "object",
            "properties": {
                "country_id": {
                    "type": "integer"
                }
            }
        },
        "httpgin.Delete_CountryById_Request": {
            "type": "object",
            "properties": {
                "country_id": {
                    "type": "integer"
                }
            }
        },
        "httpgin.Delete_CountryById_Response": {
            "type": "object",
            "properties": {
                "country_title": {
                    "type": "string"
                }
            }
        },
        "httpgin.Error_Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                }
            }
        },
        "httpgin.Filter": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "httpgin.Get_All_Country_Request": {
            "type": "object",
            "properties": {
                "filter": {
                    "$ref": "#/definitions/httpgin.Filter"
                },
                "pagination": {
                    "$ref": "#/definitions/httpgin.Pagination"
                },
                "sort": {
                    "$ref": "#/definitions/httpgin.Sort"
                }
            }
        },
        "httpgin.Get_All_Country_Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpgin.Get_CountryById_Response"
                    }
                },
                "error": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/httpgin.Pagination"
                }
            }
        },
        "httpgin.Get_CountryById_Response": {
            "type": "object",
            "properties": {
                "country_area": {
                    "type": "string"
                },
                "country_capital": {
                    "type": "string"
                },
                "country_id": {
                    "type": "integer"
                },
                "country_title": {
                    "type": "string"
                }
            }
        },
        "httpgin.Pagination": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "httpgin.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "httpgin.Sort": {
            "type": "object",
            "properties": {
                "by": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                }
            }
        },
        "httpgin.Update_CountryById_Request": {
            "type": "object",
            "properties": {
                "country_area": {
                    "type": "string"
                },
                "country_capital": {
                    "type": "string"
                },
                "country_id": {
                    "type": "integer"
                },
                "country_title": {
                    "type": "string"
                }
            }
        },
        "httpgin.Update_CountryById_Response": {
            "type": "object",
            "properties": {
                "country_area": {
                    "type": "string"
                },
                "country_capital": {
                    "type": "string"
                },
                "country_title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "hackatonsite.jumpingcrab.com:18000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "country API",
	Description:      "API с документацией Swagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
